// Generated by https://quicktype.io

using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;

namespace Server.Models
{
    public interface IDataFile
    {
        IEnumerable<IScreenData> GetAll();
        IScreenData Get(Func<IScreenData, bool> searchFunc);
        IScreenData GetByKey(string key);
        string Serialize();
        void CreateOrUpdate(IScreenData screenData);
        void CreateOrUpdate<T>(JObject screenData) where T : IScreenData;
    }
}